services:
 north:
  container_name: north
  build:
      context: .
      dockerfile: Dockerfile
  restart: unless-stopped
  volumes:
      - ./db.sqlite3:/application/db.sqlite3
      - ./media:/application/media
  ports:
   - "8000:8000"
